### ISSUE TITLE
Cannot locate user file loop

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#53] opened 2017-08-27 12:06 UTC
When I start NMC it says it cannot find user files. When I pick PC and select the user file install it restarts but repeats the last dialogue. If I cancel from it and try to select paths thru the menu I get the same results. Re-installing did not help. Not sure if relevant but sometime right before this I had re-saved my latest Home Base.

Windows 10 pro
C:\Users\Steve\AppData\Roaming\HelloGames.
D:\Program Files (x86)\Steam1\steamapps\common\No Man's Sky.

[Settings.txt](https://github.com/jaszhix/NoMansConnect/files/1254369/Settings.txt)

[NMC.txt](https://github.com/jaszhix/NoMansConnect/files/1254371/NMC.txt)

- How can this bug be reproduced?

**Comment by kraziflip** [comment] 2017-09-14 17:18
This happened to me too. While the option to pick between PC and PS4 is up look for options (wrench button). Click that and make sure you set the difficulty that you have a save on (normal, survival, permadeath etc). This should restart the app. if not go ahead and set the save file directory again to force it to restart.

**Comment by ukmerlin** [comment] 2017-09-14 19:26
Since this I had completely uninstalled the app, deleted all files / caches in install directory and user files and reinstalled and got it to work again. Now I mainly stay offline to keep it stable and now and then go online to sync data.

**Comment by jaszhix** [comment] 2017-09-27 23:06
Might be fixed in 0.18.0, I fixed a similar condition when selecting PS4 mode with a PC profile, the two conditions may be related.

**Comment by geho** [comment] 2017-10-10 13:55
For me it happened after cleaning old save data. Maybe NMS 1.38 filenames are incompatible?
Since 1.38: 
mf_save*.hg
save*.hg
Previously:
mf_storage*.hg
storage*.hg

**Comment by jimmon89** [comment] 2017-10-12 03:42
what geho mentioned is indeed one of the causes of the issue, renamed
mf_save*.hg ==>mf_storage*.hg
and
save*.hg ==> storage*.hg
and it stops looping

**Comment by jaszhix** [comment] 2017-10-12 18:19
Yes, this was a last minute change before 1.38 left experimental, I will need to update NMC.

**Comment by jimmon89** [comment] 2017-10-12 18:20
fair enough, take your time

**Comment by jaszhix** [comment] 2017-10-25 04:01
I haven't reproduced the file request loop in a while.

@ukmerlin Is this still an issue in v0.19.0?

The other issue with locations not updating is fixed in [v0.19.0](https://github.com/jaszhix/NoMansConnect/releases/tag/v0.19.0).

**Comment by ukmerlin** [comment] 2017-10-25 20:55
I had not replicated the problem from the second posting onwards since the complete deletion and reinstallation. Not sure what triggered it originally so I would suggest this could be closed......

**Closed** 2017-10-25 22:13 UTC
Labels: bug
