### ISSUE TITLE
Problems with v.8.0

### ISSUE THREAD

**Issue by psgrace** [jaszhix/NoMansConnect#18] opened 2017-05-11 04:22 UTC
I am having problems with NMC 0.8.0, which is odd because it seemed to be working well when first installed. The only change to my system has been an update to the Nvidia driver.

First, the program is taking a really long time to boot up. 50 seconds for lists to appear, 65 seconds for galactic map, 3 min 40 sec before mouse clicks are registered.
The program then works normally for some time, but eventually ceases to function. Last night for example, I started the program at 7.46 PM. It registered discoveries until just before midnight, but failed to register two made between 12.00 and 1.00AM.
When I closed NMS and attempted to maximise NMC from the taskbar, I just got a white rectangle the size of the NMC window. I could then do nothing except close the program from the taskbar. On other occasions I have not had NMC minimised; I then see the white rectangle when I close NMS.  
Looking at the error log, I see that the install path has not been found. I have manually re-entered it, with no effect. This in itself does not seem to stop the program working though. There seems to be nothing in the log when the program stops working.

[NMC.txt](https://github.com/jaszhix/NoMansConnect/files/991851/NMC.txt)

I re-started NMC to check whether locations had been recorded; as I said, it had worked for some hours then stopped. 

Checking in my Task Manager, I see that NMC generates two background processes, and one of these is using 30%-40% of the CPU and 700-1000Mb of memory. Is this normal? It seems rather a lot. When NMS is running as well, the CPU is often going over 95%.

The slow start and the high CPU usage happen every time. The loss of the UI and failure to record locations has also happened every time, but after varying periods of normal operation. I have tried re-installing NMC; made no difference. 

Windows 10

C:\Users\New\AppData\Roaming\HelloGames\NMS\DefaultUser

C:\GOG Games\No Man's Sky

**Comment by jaszhix** [comment] 2017-05-11 06:43
When you say the locations are not registering, are they saving locally? This looks like a server issue. The main problem is:

```"AJAX Worker failure: pollRemoteLocations"```

That means its not contacting the server. The app will work anyway, then re-sync the locations the next time it starts up if there's a connection. The CPU usage is a problem with the app doing things on a schedule, and problems optimizing with Electron. The app sends a small request to the server with time stamp info every 30 seconds, and the server checks if there were new locations since that time. If so, it sends them back to the client. This can be improved of course, but it might require sacrificing some frequency of updates. Maybe it can be an option with a slider.

**Comment by psgrace** [comment] 2017-05-11 07:31
No, they are not saving locally. The app is completely ceasing to function at some point, with the UI disappearing, leaving just a big white rectangle. Everything that _has_ saved locally is also going on the "recent explorations" list, so I guess the server is being contacted sometimes.
I asked about the CPU usage because it seemed high, but if that is normal behavior, fine. Does the error with the install path matter?

**Comment by jaszhix** [comment] 2017-05-11 07:56
Can you try this build? It doesn't do anything different except return more verbose logging to NMC.log if there's errors. https://www.mediafire.com/?pda2h6de0jxon22

**Comment by jaszhix** [comment] 2017-05-11 07:57
The install path may be caused by your save data directory being set incorrectly, but the fallback path is working. But the logging of that itself is a bug.

**Comment by psgrace** [comment] 2017-05-11 08:52
OK, loaded new build. Same so far; 4 minutes to boot but seems to be working. Log so far:

Thu May 11 2017 18:34:01 GMT+1000 (Tasmania Standard Time):    "Initializing No Man's Connect 0.8.0"
Thu May 11 2017 18:34:01 GMT+1000 (Tasmania Standard Time):    "Failed to locate NMS install: path doesn't exist."
Thu May 11 2017 18:34:04 GMT+1000 (Tasmania Standard Time):    "Active save file: C:\\Users\\New\\AppData\\Roaming\\HelloGames\\NMS\\DefaultUser\\storage3.hg"
Thu May 11 2017 18:34:04 GMT+1000 (Tasmania Standard Time):    "Username: pgrace"
Thu May 11 2017 18:34:04 GMT+1000 (Tasmania Standard Time):    "Current location: 75:0:-150:0:76:0"
Thu May 11 2017 18:34:19 GMT+1000 (Tasmania Standard Time):    "AJAX Worker failure: handleSync"
Thu May 11 2017 18:37:42 GMT+1000 (Tasmania Standard Time):    "AJAX Worker failure: pollRemoteLocations"
Thu May 11 2017 18:41:34 GMT+1000 (Tasmania Standard Time):    "AJAX Worker failure: pollRemoteLocations"
Thu May 11 2017 18:42:20 GMT+1000 (Tasmania Standard Time):    "AJAX Worker failure: pollRemoteLocations"
  
I'll comment again when it fails.

**Comment by CrankyCat** [comment] 2017-05-12 00:50
No UI crashing, fortunately, but it does seem to stall temporarily while I'm seeing ""AJAX Worker failure: fetchRemoteLocations" with high cpu usage.

**Comment by jaszhix** [comment] 2017-05-12 01:11
Did the UI crash for you before today? I'm testing a change on the server currently that handles an error better (that will be fixed properly in the next client update).

**Comment by CrankyCat** [comment] 2017-05-12 01:14
Nothing before today here. It hasn't happened, perhaps coincidentally, since I removed the "run as administrator" flag.

**Comment by psgrace** [comment] 2017-05-12 04:05
CrankyCat, yes I change my shortcut so it always runs as administrator. When I loaded the new build last night though it ran from the instal, before I adjusted the shortcut, and still behaved the same (really slow bootup, constant high CPU usage).
Last night the UI didn't fail in a fairly short session. I'll see how it goes over a longer one today.

**Comment by jaszhix** [comment] 2017-05-12 04:16
I think I have the high CPU (and hopefully crashing because I think they're related) figured out. Going drop a test build here soon.

**Comment by jaszhix** [comment] 2017-05-12 04:33
Here's the new test build: https://www.mediafire.com/?m1im9is35wna4r3

**Comment by psgrace** [comment] 2017-05-12 07:56
My UI just crashed while I was watching Task Manager, The second background process was using 40% CPU, 1.8Gb memory (compared with NMS itself using 58% CPU, 1.6Gb memory) and it suddenly just vanished. The UI disappeared, leaving a white rectangle. The foregound app and the other background process continued, using almost no resources, until I closed the app from the taskbar. This generated nothing in the error log.
Here is the error log from when I booted up today. The crash took place about 17.30 local time.

Fri May 12 2017 13:29:30 GMT+1000 (Tasmania Standard Time):    "Initializing No Man's Connect 0.8.0"
Fri May 12 2017 13:29:30 GMT+1000 (Tasmania Standard Time):    "Failed to locate NMS install: path doesn't exist."
Fri May 12 2017 13:29:33 GMT+1000 (Tasmania Standard Time):    "Username: pgrace"
Fri May 12 2017 13:29:33 GMT+1000 (Tasmania Standard Time):    "Active save file: C:\\Users\\New\\AppData\\Roaming\\HelloGames\\NMS\\DefaultUser\\storage2.hg"
Fri May 12 2017 13:29:33 GMT+1000 (Tasmania Standard Time):    "Current location: 75:0:-150:0:354:4"
Fri May 12 2017 13:29:48 GMT+1000 (Tasmania Standard Time):    "AJAX Worker failure: handleSync"

I see you have put up a new build; I'll give it a try.

**Comment by psgrace** [comment] 2017-05-12 08:32
New build looking better; 30 sec to boot, background process cycling 0 to 10% CPU, 180Mb memory. 
Error log still gives "AJAX Worker failure: handleSync"
All my locations have appeared on the map, but most shared (blue dot) have not. I can see about 40 blue dots.

**Comment by jaszhix** [comment] 2017-05-12 08:51
Ah, cool. Maybe the remote cache was reset?

**Comment by CrankyCat** [comment] 2017-05-12 15:38
@psgrace The locations can be reloaded by scrolling down all of the locations until you get to the end. That's probably not practical at some point though.

@jaszhix  Is that what "Sync Locations" is supposed to do? It doesn't seem to do anything atm.

**Comment by jaszhix** [comment] 2017-05-12 20:56
Sync location only syncs your own locations. It checks unpublished locations locally, and remote locations needing downloading.

**Comment by CrankyCat** [comment] 2017-05-13 03:48
Actually, now that I've tried v9 it seems to reset the cache every time I exit or just not write it out to the file. After I restart only the locations initially loaded are shown on the map. If I had more locations previously then they are gone.

**Comment by jaszhix** [comment] 2017-05-13 04:06
Oh fun, I can only reproduce this in the production build.

**Comment by jaszhix** [comment] 2017-05-13 04:39
Okay, fixed :) https://www.mediafire.com/?y6rhl85vqsnrzb2

**Comment by psgrace** [comment] 2017-05-13 07:41
Running 0.9.0 Beta 2, all seems well. It has gone back to taking several minutes to become responsive, but I guess that is the price of loading all the locations in. Once fully initialized it is behaving normally. It does still log the error "AJAX Worker failure: handleSync" on bootup.

**Comment by jaszhix** [comment] 2017-05-13 08:22
Yeah, the cache has become a bottle neck. I'm looking into ways to load the actual data by chunks so its not blocking I/O.

**Comment by CrankyCat** [comment] 2017-05-13 11:46
Maybe cache the images on a different server and gzip blocks of locations and return the block from the server?

**Comment by jaszhix** [comment] 2017-05-13 18:16
The problem isn't the server - it already has gzipping enabled in nginx. Its caused by loading a 10MB+ JSON file. This is being loaded in another thread asynchronously, but it still blocks the UI when its loading it.

**Closed** 2017-05-14 18:41 UTC
Labels: bug, enhancement
