### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by ExxessiveGK** [jaszhix/NoMansConnect#126] opened 2019-08-24 18:53 UTC
upon first install and opening connect it worked fine. eve since closing it it just opens with a blacscreen

**Comment by jaszhix** [comment] 2019-08-24 18:57
I can help, but you need to fill out the [issue template](https://github.com/jaszhix/NoMansConnect/blob/master/ISSUE_TEMPLATE.md).

**Comment by ExxessiveGK** [comment] 2019-08-24 19:34
I will have to look over those files before i will release them to make sure there is no personal info I do not want handed out but I will say its the program itself and I found that if you click the top of the program even when its black screen it eventually shows the program

I recorded the bug to visually show you.
https://imgur.com/ci7ROXF

**Comment by jaszhix** [comment] 2019-08-24 19:38
At a minimum, please try to explain steps to reproduce the bug. What were you doing leading up to this happening? I can't help without debug info or context.

**Comment by ExxessiveGK** [comment] 2019-08-24 19:44
installed latest version of connect. C:\drive
have latest version of GOG NMS beyond.
Read through connect read files saying you can start connect without game running.
Launched connect, tested read save files through connect, everything worked fine.
Next looked at galaxy map double clicked on it and it bugged out.
proceeded to click on 3d map beta, connect completely went unresponsive.
Forced a shutdown on connect.
relaunched and black screen bug as shown in video.

uninstalled connect, wiped any remnant of program in registry.
reinstalled after restart same exact results.

**Comment by ExxessiveGK** [comment] 2019-08-24 19:59
ok so I decided to test a theory with dual gpu problems with high end gaming laptops.
Fivem was known for having this issue as well with dual gpu gaming laptops.

and the bug is in fact connect reads the first gpu and not the dedicated gpu on high end gaming latop. so you have to force connect to read the dedicated gpu on laptops just like Fivem program

https://imgur.com/SlPQiQp

bug fix for gaming laptop

**Comment by jaszhix** [comment] 2019-08-24 20:06
Is this an Nvidia GPU? I switched NMC to OpenGL rendering so there's wasn't a DirectX translation occurring for the 3D map, but I've noticed recently this might be causing issues on driver versions after 419.

**Comment by ExxessiveGK** [comment] 2019-08-24 20:12
Yes I have the Intel GPU and 2 Nvidia GPU with a total of 3 GPU's on this laptop.
 I had the same issues with my Fivem program for GTAV and found the end user has to set their Fivem manually through Nvidia control panel and force it to use high end gpu in 3d setting..

 I have yet to test this on my desktop, but I'm assuming just like Fivem it only happens on gaming laptops.

**Comment by jaszhix** [comment] 2019-09-29 00:27
Can't reproduce this and the author seems to have a workaround in place, so closing for now. Feel free to open a new issue, or ping here if you have further trouble with this.

**Comment by jaszhix** [comment] 2019-11-08 22:25
Started noticing Chrome has been crashing with OpenGL when fullscreening videos, and the newest version of Visual Studio Code is crashing when maximized when running with `--use-angle=gl` flag, appearing in Chromium 75. This seems to be the same cause. The 3D map has to resize itself when it renders, but currently there's a bug where the GL context gets reset and the resize function in the ANGLE renderer doesn't assume that.

https://bugs.chromium.org/p/chromium/issues/detail?id=1004117

**Closed** 2020-01-12 20:19 UTC
Labels: bug, upstream
