### ISSUE TITLE
Recents Panel Not Updating

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#64] opened 2017-11-14 17:15 UTC
The right pane showing recent discoveries is not updating. The left panel showing own discoveries is updating. Changing right panel for favourites, Home Base etc also does not change the content of the right panel.
The last discovery updated was November 8th.
Windows 10 pro

**Comment by mcsneedy** [comment] 2018-02-20 21:36
Getting the same issue since going to Eissentam at the end of Atlas purge (wasn't happening in Euclid). The 2D galactic map doesn't update, nor does the right-hand panel. 'Stored locations' is updating though.

**Comment by jaszhix** [comment] 2018-02-20 22:48
Hi, can you guys provide your `nmc.log` and `settings.json` in `YourUser/AppData/Roaming/NoMansConnect`? Thanks.

**Comment by MickCasanova** [comment] 2018-02-24 22:51
I've had this issue through at least the last two versions. It sits on loading locations, and they never update. I haven't played in months, and the problem persists with the latest version.
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/1755401/NMC.log)

**Comment by MickCasanova** [comment] 2018-02-27 14:54
Well, I did something as a last resort, and it seems to have worked. I renamed the \Appdata\Roaming\NoMansConnect folder, and allowed the application to create a new one. Suddenly everything began to work again. I don't seem to have lost any locations, and all of my user data remains intact.

Just thought I'd share my findings... If anything goes wacky, I'll be sure to report it here.

**Comment by djehmli** [comment] 2018-03-03 18:40
My Recent Explorations stopped updating between ver 1.00 and 1.02, since my locations were updating I just ignored the Recent Explorations being stagnate.  I just did the same thing MickCasanova did by renaming the old NoMansConnect folder and wallah, right hand side panel began working again.  (I've kept the old folder as a backup, but so far all my personal locations are there)

**Comment by jaszhix** [comment] 2018-03-03 18:59
How many explorations are cached under Recent Explorations when this happens? It should say it in parenthesis next to "Recent Explorations".

**Comment by MickCasanova** [comment] 2018-03-03 23:16
I noticed something peculiar in the Recent Explorations panel Mine had no number in parenthesis. There was nothing. I know it was there before. I decided to "reset remote cache". When I did that, NMC restarted, and I was suddenly back to where I was a few days ago when the panel stopped updating. So I again renamed the folder like I mentioned before. When I did this, it appeared to return to normal once again. 

Somehow I get the feeling that things aren't updating properly. When the new list came up, it included more recent explorations with today's date.. Before I did that, (I just did this in the last hour) the most recent exploration that showed was Feb 27th. Not sure if any of this is significant, just thought it might be helpful to post an observation.

**Comment by djehmli** [comment] 2018-03-04 03:23
Currently, with a fresh renamed folder - 789 Recent explorations, 611 stored locations.

I had reset the remote cache on 2/17/18,

**Comment by MickCasanova** [comment] 2018-03-04 16:43
Just opened NMC and noticed 537 cached locations, and 185 stored, as well a list of them with the current date. I haven't opened NMS yet, but this is the first time in days that I've opened it up and saw new locations with current dates. I'll keep and eye, and note any inconsistencies.

I just have to mention that without NMC, I don't enjoy NMS as much. NMC is an essential tool that really makes playing NMS enjoyable for me. Thanks for this wonderful utility, you've done everyone a great service.

**Comment by mcsneedy** [comment] 2018-03-05 09:19
Hi there - can I email them to you?

**Comment by mcsneedy** [comment] 2018-03-06 04:39
Also - it won't let me manually register a valid galactic address. Eg for Eissentam: "0D54:0007:0D54:00EE" gives "Invalid coordinate format"

**Comment by jaszhix** [comment] 2018-03-06 17:22
Feel free to email. I suspect resetting the profile data is a short-term fix, it will eventually occur again, so being able to reproduce it is important for it getting fixed.

The issue about invalid coordinates could go into a separate issue, not sure that's related to this one.

**Comment by mcsneedy** [comment] 2018-03-08 07:13
Thanks - do I use notifications@github.com or another email address?

**Comment by MickCasanova** [comment] 2018-03-13 18:45
I've been having to delete the mentioned folder every two days. Now I haven't been able to connect since Saturday. Keeps asking for a user name.

**Comment by jaszhix** [comment] 2018-03-14 01:35
@MickCasanova What is your username? I'll turn account protection off for you.

@mcsneedy No, email on my Github profile.

**Comment by MickCasanova** [comment] 2018-03-14 14:38
My user name is MickCasanova. Tried again this morning, and am still being prompted to enter a user name. When I do, it restarts, my name appears briefly, then it prompts me for a name again.

**Comment by MickCasanova** [comment] 2018-03-17 14:03
Thanks for the reset. I was finally able to connect just now. I might add that once I did connect, I was faced with the infinite loading locations once again. I did what I usually do and deleted the directory, and everything returned to normal. Thanks again.

**Comment by MickCasanova** [comment] 2018-03-25 13:27
Seems I can't log in again.

**Comment by jaszhix** [comment] 2018-03-25 13:31
Hi, sorry for responding late, been a little busy. I never changed your account initially. Server has an uptime of 66 days currently. Are you logging in from a different computer? When you protect your username it is tying it to the Windows installation you're currently using.

**Comment by MickCasanova** [comment] 2018-03-25 13:34
No, not logging in from a different computer. Just removed an old sound card. That's about it.

**Comment by jaszhix** [comment] 2018-03-25 13:37
I probably won't be able to work on NMC until a week after April 1st. I unprotected your profile in the mean time.

**Comment by MickCasanova** [comment] 2018-03-25 13:42
Still won't allow me to log in. Thanks for trying though.

**Comment by jaszhix** [comment] 2018-03-25 13:50
OK, I will probably be switching to a simpler password login system soon. In the mean time, repeating the steps before of clearing your NoMansConnect folder should work, but back it up in case before you try that.

**Comment by MickCasanova** [comment] 2018-03-25 14:21
Didn't work this time.. I'll be patent. Thanks though.

**Comment by MickCasanova** [comment] 2018-03-29 20:28
Interesting... Although I'm still unable to log in, locations indicating I've been on have appeared in my location list as of March 28. I literally haven't been on since the 23rd. Perhaps someone has hijacked me?

**Comment by MickCasanova** [comment] 2018-03-30 16:07
I'm not entirely sure where in the Settings.json this information is. It was easy enough to find the MachineGuid in the registry, but I could find nothing remotely resembling that number, or any of the numbers you provided in the Settings.json file.

**Comment by MickCasanova** [comment] 2018-04-02 21:05
The only number I see that is consistent in all of my saved NMC directories is "maintenanceTS"

**Comment by MickCasanova** [comment] 2018-04-06 21:06
I've noticed something that appears to happen quite frequently. While I've only had my account working since yesterday, I have logged in more than a few times. Probably five times. The first few times, "recent explorations" appeared to update properly. I was seeing entries from people other than myself. The last time I logged in yesterday, I noticed no new entries. All I saw were only my own near the top. Just a moment ago when I logged in, I noticed the number next to "recent explorations" had vanished (it had previously read over 500), and still only my explorations had shown since yesterday. So I deleted the folder I have mentioned in previous posts in this thread, and restarted.  Now I see 23 new entries other than my own above me. This is a repeating pattern. I still need to delete and restart to get the most recent explorations, and to make the number of entries to the right reappear after a time.

**Comment by jaszhix** [comment] 2018-04-07 01:06
The app slows down a lot after you hit many thousands of cached remote locations. The temporary workaround was to auto-prune the cached locations until they reach 6000, once over that number the auto-pruning occurs. This might be having a side effect and pruning locations that are recent, not by oldest, like its supposed to.

What I intend to do next is migrate all client data to SQLite, which will help alleviate the original issue of slow I/O with tons of locations.

**Comment by MickCasanova** [comment] 2018-04-09 13:18
I've logged in perhaps 10 times or so, and am pleased to report that I have seen new locations load each time, and have not found the need to "delete" my NMC directory to recover a stuck "Recent Locations" list. Time will tell, but so far everything seems to be working as intended.

**Comment by MickCasanova** [comment] 2018-04-10 14:32
Have yet to run into any issues. NMC appears to be stable, and updating properly. Every time I log in, my "Recent Explorations" list updates. The number to the right showing the number of explorations loaded, has not vanished again. Also like being able to see how many entries others have contributed. So far so good. :)

**Comment by jaszhix** [comment] 2018-04-10 14:46
Cool, sounds good! I've been running the app for a couple days, and everything seems to be staying in sync with the server. I'll go ahead and close this. Thanks for the feedback.

**Closed by jaszhix** 2018-04-10 14:46 UTC
Labels: bug
