### ISSUE TITLE
[PS4 mode auth] Invalid username protection

### ISSUE THREAD

**Issue by itsmeow** [jaszhix/NoMansConnect#51] opened 2017-08-26 04:29 UTC
so the username for PS4 "hiotewdew" is protected. It is MOST DEFINITELY mine and literally no one else uses it and the likelihood of anyone else using it for NMS on PS4 is ZERO because it is me.
Proof: http://prntscr.com/gd6bqm http://prntscr.com/gd6bu6

**Comment by itsmeow** [comment] 2017-08-26 04:31
Actually basically everything is broken and it says "fgasgad" is protected so I don't know what is UP with your thing so uh closing issue

**Comment by jaszhix** [comment] 2017-08-26 12:43
Just an FYI you can associate an email address with your profile, bu that doesn't seem to be the issue. On the server console this is what I see:

```
>>> x = NMSProfile.objects.get(username='fgasgad')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
project.main.models.DoesNotExist: NMSProfile matching query does not exist.
```
There is a known issue with using the PS4 mode and authentication.

**Comment by jaszhix** [comment] 2017-08-26 12:48
Also, if you see your machine_id in your logs I can look it up that way, sometimes it doesn't match the username up correctly when there's no save file to work with.

**Comment by jaszhix** [comment] 2017-09-13 22:55
Closing since this is likely a duplicate of #48.

**Closed by jaszhix** 2017-09-13 22:55 UTC
