### ISSUE TITLE
[Windows 7] NMC 1.3.0 stuck in "checking for mods" loop 

### ISSUE THREAD

**Issue by MickCasanova** [jaszhix/NoMansConnect#83] opened 2018-08-04 15:26 UTC
Issue template for bug reports:

- Description of the problem: NMC 1.3.0 stuck in "checking for mods" loop 
- Windows version: Windows 7
- Absolute path to your storage_x.hg files.: C:\Users\MC\AppData\Roaming\HelloGames\NMS\DefaultUser 
- Absolute path to your NMS install directory.: E:\GoG\No Man's Sky\

Program stuck in endless loop at start.

You can see from the log that 1.21 starts and runs flawlessly. 1.3.0 however, does not. I am always prompted with the option to send recovery email or enter token. NMC never returns from the loop. 

[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2259573/NMC.log)

[settings.log](https://github.com/jaszhix/NoMansConnect/files/2259574/settings.log)

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json

- How can this bug be reproduced?

**Comment by MickCasanova** [comment] 2018-08-04 15:32
fyi.. settings.log is settings.json since this site doesn't support uploading .json

**Comment by jaszhix** [comment] 2018-08-04 16:03
Ah, this one I can actually explain. In the server code, I made Explorer a reserved profile with the 1.3.0 deployment because I needed a default profile to associate the locations to - otherwise it causes too many bugs as everything expects a profile association in the client code. I changed this to a profile called "Blackhole" where all orphaned locations go now. Please let me know how the change works.

**Comment by MickCasanova** [comment] 2018-08-04 16:32
I did as you suggested, and allowed 1.3.0 to rebuild the AppData/Roaming/NoMansConnect directory, and it's back to this....
Sat Aug 04 2018 11:26:38 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 1.3.0"
Sat Aug 04 2018 11:26:38 GMT-0500 (Central Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Aug 04 2018 11:26:38 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Sat Aug 04 2018 11:26:39 GMT-0500 (Central Daylight Time):    "Request failed with status code 403"
Sat Aug 04 2018 11:26:39 GMT-0500 (Central Daylight Time):    "Username protected: Explorer"
Sat Aug 04 2018 11:27:23 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 1.3.0"
Sat Aug 04 2018 11:27:23 GMT-0500 (Central Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Aug 04 2018 11:27:23 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Sat Aug 04 2018 11:27:24 GMT-0500 (Central Daylight Time):    "Request failed with status code 403"
Sat Aug 04 2018 11:27:24 GMT-0500 (Central Daylight Time):    "Username protected: Explorer"
Sat Aug 04 2018 11:28:08 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 1.3.0"
Sat Aug 04 2018 11:28:08 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Sat Aug 04 2018 11:28:09 GMT-0500 (Central Daylight Time):    "Request failed with status code 403"
Sat Aug 04 2018 11:28:09 GMT-0500 (Central Daylight Time):    "Username protected: Explorer"
Sat Aug 04 2018 11:28:56 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 1.3.0"
Sat Aug 04 2018 11:28:56 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Sat Aug 04 2018 11:28:57 GMT-0500 (Central Daylight Time):    "Request failed with status code 403"
Sat Aug 04 2018 11:28:57 GMT-0500 (Central Daylight Time):    "Username protected: Explorer"

Interestingly, I get the prompt for the email the moment I start NMC... It occurs to me that it's never going to send me a response if it's looking for "Explorer" as the user...

**Comment by jaszhix** [comment] 2018-08-04 16:40
Okay, I'll to try to reproduce this locally.

**Comment by jaszhix** [comment] 2018-08-04 17:06
I was able to login to your profile locally using the dev environment after explicitly pointing the save file in the right direction. This is tricky because NMC is very sync happy - its a convenience for everyone but a pain to debug different user profiles with. As a result I can 100% mimick your environment with your save file. If you can email it to me (on my profile) it would help accelerate the puzzle solving. What happens when you go into the menu and select "Override username" and enter "MickCasanova"?

**Comment by jaszhix** [comment] 2018-08-04 17:15
By the way, I develop on and am targeting Windows 10 and Linux primarily. I have some workarounds in place for odd Windows 7 quirks which might make this even more complicated, so ultimately no fix is guarunteed here - so the more files I can use for debugging the easier it is. On top of that, I don't have the GOG version of NMS.

**Comment by MickCasanova** [comment] 2018-08-04 17:28
Sent the save to you via your email on your profile...

**Comment by MickCasanova** [comment] 2018-08-04 17:31
Both the GoG and Steam version of the game are functionally identical. It's just where they put it that's different.... Plus, the GoG version doesn't force updates.

**Comment by jaszhix** [comment] 2018-08-04 17:33
GoG version sets everyone's username as Explorer.

**Comment by jaszhix** [comment] 2018-08-04 17:49
![image](https://user-images.githubusercontent.com/6859057/43679094-b7256b38-97e4-11e8-8547-e07d12011cc7.png)

I took a fresh snapshot of the production DB, loaded it into the server. Changed our auth keys. Loaded your save file and settings. It asked for your username at first, then loaded the profile. I honestly don't know where to go from here, and its looking like a Windows 7 problem.

**Comment by jaszhix** [comment] 2018-08-04 18:09
It could be something else entirely different specific to your environment too. 1.2.1 should be working for a while, but there's no guarantee. Because NMC 1.3 allows teleporting to multiple places per planet there will be a slow migration of locations that will break on 1.2.1 eventually.

Windows 7 goes EOL in a little over a year, and I believe W10's market share has finally surpassed it. Going to close this since I think I'm not going to be able to chase this one without VM headache, and don't want to give false hope.

**Comment by jaszhix** [comment] 2018-08-05 11:57
@MickCasanova @KingCronus1270 Can you please test this version and see if it works for you? Thanks.

https://www.mediafire.com/file/42355dkxih0566o/NoMansConnect+Setup+1.3.1-rc.exe

**Comment by KingCronus1270** [comment] 2018-08-05 12:32
I tried it, still got the same error on start, still stuck on loading, and
won't let me override username, thanks for the quick reply though.

**Comment by jaszhix** [comment] 2018-08-05 12:33
@KingCronus1270 Can you attach NMC.log in AppData/Roaming/NoMansConnect?

**Comment by KingCronus1270** [comment] 2018-08-05 12:48
Here ya go.

**Comment by jaszhix** [comment] 2018-08-05 13:03
@KingCronus1270 Don't think I received anything - can you attach it on the Github website?

**Comment by jaszhix** [comment] 2018-08-05 13:11
@MickCasanova @KingCronus1270  Actually, I think I found the issue with my first attempted fix. Can you test this version? http://www.mediafire.com/file/t2xa02uaaaa848w/NoMansConnect+Setup+1.3.1-rc.exe

**Comment by KingCronus1270** [comment] 2018-08-05 13:15
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2260343/NMC.log)

**Comment by MickCasanova** [comment] 2018-08-05 16:31
Holy crap, it works! Thanks a bunch... I missed all the excitement because I was out.. Came on this morning to see a boatload of posts in my email... I loaded 1.3.1 rc1 and it fired up immediately. Thanks for your persistence.

**Closed** 2018-08-05 18:41 UTC
