### ISSUE TITLE
Stuck in cannot locate save data

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#136] opened 2019-09-12 18:39 UTC
Unless this is a feature request, ALL of the following is required:

- Once I did an in game manual save the machine jumped to the dialogue box for this. And game crashed and restarting NMC and game with path set still returns to this. 
- Windows version 10
- NMC version Beyond 2.11
- Absolute path to your storage_x.hg files.
C:\Users\steve\AppData\Roaming\HelloGames\NMS\st_7656119832812xxxx
- Absolute path to your NMS install directory.
D:\Program Files (x86)\Steam\steamapps\common\No Man's Sky\GAMEDATA
[settings.zip](https://github.com/jaszhix/NoMansConnect/files/3606979/settings.zip)

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- settings.json

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?

**Comment by jaszhix** [comment] 2019-09-29 00:25
Not able to reproduce this currently, closing for now. Feel free to open a new issue or ping here if you have further trouble with this.

**Closed by jaszhix** 2019-09-29 00:25 UTC
Labels: bug
